### ISSUE TITLE
Akamai SDK build timeout due to CPU/Memory starvation in GitHub Actions?

### ISSUE THREAD

**Issue by jooooel** [pulumi/pulumi-akamai#366]
### What happened?

I'm trying to run pulumi up/preview in GitHub Actions, but there seems to be some issues with building the Pulumi Akamai Go SDK.

The job is stuck for a really long time and it looks like nothing happens. After a while (close to an hour maybe), the job fails and I get the following error:

```
The hosted runner: GitHub Actions 2 lost communication with the server. Anything in your workflow that terminates the runner process, starves it for CPU/Memory, or blocks its network access can cause this error.
```

### Example

I have narrowed it down to building `github.com/pulumi/pulumi-akamai/sdk/v6/go/akamai`. Here is a minimal reproduction. One part is the `main.go` file of the Pulumi application (I guess it doesn't matter that it's Pulumi in this case). And the other part is the config for a GitHub Action that can trigger the issue.

```go
package main

import (
	"github.com/pulumi/pulumi-akamai/sdk/v6/go/akamai"
)

func main() {
	_ = akamai.Property{}
}
```

```yaml
name: "Test"

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - name: Build
        run: |
          go build -v -o goapp
```

### Output of `pulumi about`

Not really relevant I guess...

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
